# Generated by Django 4.0 on 2021-12-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_instacook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='direction',
            new_name='directions',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='number_of_servings',
            new_name='num_of_servings',
        ),
    ]
